// Base de datos
const productos = [
    {
        id: 1,
        cantidad: 1,
        nombre: "sneaker1",
        precio: 700,
        imagen: "./assets/productos/producto-1.webp",
        color: "blanco",
        estrellas: 5,
        tallas: [23,24,25,26,27,28],
    },
    {
        id: 2,
        cantidad: 1,
        nombre: "sneaker2",
        precio: 750,
        imagen: "./assets/productos/producto-2.webp",
        color: "negro",
        estrellas: 5,
        tallas: [23,24,25,26,27,28],
    },
    {
        id: 3,
        cantidad: 1,
        nombre: "sneaker3",
        precio: 600,
        imagen: "./assets/productos/producto-3.webp",
        color: "gris",
        estrellas: 4,
        tallas: [23,24,25,26,27,28],
    },
    {
        id: 4,
        cantidad: 1,
        nombre: "sneaker4",
        precio: 650,
        imagen: "./assets/productos/producto-4.webp",
        color: "cafe",
        estrellas: 5,
        tallas: [23,24,25,26,27,28],
    },
    {
        id: 5,
        cantidad: 1,
        nombre: "sneaker5",
        precio: 500,
        imagen: "./assets/productos/producto-5.webp",
        color: "rojo",
        estrellas: 3,
        tallas: [23,24,25,26,27,28],
    },
    {
        id: 6,
        cantidad: 1,
        nombre: "sneaker6",
        precio: 400,
        imagen: "./assets/productos/producto-6.webp",
        color: "verde",
        estrellas: 3,
        tallas: [23,24,25,26,27,28],
    },
    {
        id: 7,
        cantidad: 1,
        nombre: "sneaker7",
        precio: 450,
        imagen: "./assets/productos/producto-7.webp",
        color: "rosado",
        estrellas: 4,
        tallas: [23,24,25,26,27,28],
    },
    {
        id: 8,
        cantidad: 1,
        nombre: "sneaker8",
        precio: 600,
        imagen: "./assets/productos/producto-8.webp",
        color: "azul",
        estrellas: 5,
        tallas: [23,24,25,26,27,28],
    },
];
